/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atmproject;

/**
 *
 * @author Arddhana Zhafran
 */
public class Tarik extends javax.swing.JFrame {

     Password tabungan = new Password();
     int tabu = tabungan.tabungan;
    /**
     * Creates new form Tarik
     */
    public Tarik() {
        initComponents();
        
        hilang.setVisible(false);
        tidak.setVisible(false);
        lagi.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        setor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        salah = new javax.swing.JTextArea();
        lagi = new javax.swing.JButton();
        tidak = new javax.swing.JButton();
        hilang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MASUKKAN JUMLAH PENARIKAN");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 20, 280, 70);

        setor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(setor);
        setor.setBounds(10, 80, 470, 70);

        jButton1.setText("LANJUTKAN");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 170, 470, 50);

        salah.setEditable(false);
        salah.setBackground(new java.awt.Color(0, 102, 102));
        salah.setColumns(20);
        salah.setForeground(new java.awt.Color(255, 255, 255));
        salah.setRows(5);
        salah.setBorder(null);
        salah.setCaretColor(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(salah);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 240, 280, 130);

        lagi.setText("IYA");
        lagi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lagiMouseReleased(evt);
            }
        });
        lagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lagiActionPerformed(evt);
            }
        });
        jPanel2.add(lagi);
        lagi.setBounds(320, 380, 80, 50);

        tidak.setText("TIDAK");
        tidak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tidakMouseReleased(evt);
            }
        });
        tidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakActionPerformed(evt);
            }
        });
        jPanel2.add(tidak);
        tidak.setBounds(400, 380, 80, 50);

        hilang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hilang.setForeground(new java.awt.Color(255, 255, 255));
        hilang.setText("LAKUKAN TRANSAKSI LAGI?");
        jPanel2.add(hilang);
        hilang.setBounds(80, 370, 240, 70);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 519, 483);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
      
        int total = 50000;
        if(setor.getText().trim().isEmpty()){
            salah.setText("Mohon Masukkan Jumlah Setor yang Benar");
        
             String coba = setor.getText().toString();
             int baru = Integer.parseInt(coba);
            
        }
        else if(Integer.parseInt(setor.getText()) < total){
                salah.setText("Minimum Penarikan adalah 50000 Beserta Kelipatannya");
            
         }else{
            int tarikan = Integer.parseInt(setor.getText());
            tabu -= tarikan;

            salah.setText("");
            salah.setText("TRANSAKSI BERHASIL"
                + " \n\nSISA TABUNGAN ANDA "+tabu);

            lagi.setVisible(true);
            hilang.setVisible(true);
            tidak.setVisible(true);

        }

    }//GEN-LAST:event_jButton1MouseReleased

    private void lagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lagiActionPerformed
        
    }//GEN-LAST:event_lagiActionPerformed

    private void tidakMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tidakMouseReleased
        System.exit(0);
    }//GEN-LAST:event_tidakMouseReleased

    private void tidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakActionPerformed

    private void lagiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lagiMouseReleased
        // TODO add your handling code here:
        new Password().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lagiMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tarik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hilang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lagi;
    private javax.swing.JTextArea salah;
    private javax.swing.JTextField setor;
    private javax.swing.JButton tidak;
    // End of variables declaration//GEN-END:variables
}
