/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atmproject;

import javax.swing.JOptionPane;

/**
 *
 * @author Arddhana Zhafran
 */
public class Transfer extends javax.swing.JFrame {
    
     /*AtmProject tabungan = new AtmProject();
        int tabu = tabungan.tabungan;*/
    
    Password tabungan = new Password();
    int tabu = tabungan.tabungan;
        
    /**
     * Creates new form Transfer
     */
    int z;
    public Transfer() {
        initComponents();
        hilang.setVisible(false);
        tidak.setVisible(false);
        lagi.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        tuju = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        hilang = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salah = new javax.swing.JTextArea();
        lagi = new javax.swing.JButton();
        tidak = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NO REKENING TUJUAN");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 30, 220, 70);

        jumlah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jumlah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jumlahMouseReleased(evt);
            }
        });
        jPanel1.add(jumlah);
        jumlah.setBounds(20, 210, 450, 70);

        tuju.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tuju.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tujuMouseReleased(evt);
            }
        });
        jPanel1.add(tuju);
        tuju.setBounds(20, 90, 450, 70);

        jButton1.setText("LANJUTKAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 290, 160, 50);

        hilang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hilang.setForeground(new java.awt.Color(255, 255, 255));
        hilang.setText("LAKUKAN TRANSAKSI LAGI?");
        jPanel1.add(hilang);
        hilang.setBounds(100, 470, 240, 70);

        salah.setEditable(false);
        salah.setBackground(new java.awt.Color(0, 102, 102));
        salah.setColumns(20);
        salah.setForeground(new java.awt.Color(255, 255, 255));
        salah.setRows(5);
        salah.setBorder(null);
        salah.setCaretColor(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(salah);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 290, 280, 92);

        lagi.setText("IYA");
        lagi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lagiMouseReleased(evt);
            }
        });
        lagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lagiActionPerformed(evt);
            }
        });
        jPanel1.add(lagi);
        lagi.setBounds(340, 480, 80, 50);

        tidak.setText("TIDAK");
        tidak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tidakMouseReleased(evt);
            }
        });
        tidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakActionPerformed(evt);
            }
        });
        jPanel1.add(tidak);
        tidak.setBounds(420, 480, 80, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("JUMLAH TRANSFER");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 150, 220, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        setBounds(0, 0, 549, 577);
    }// </editor-fold>//GEN-END:initComponents

    private void jumlahMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jumlahMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahMouseReleased

    private void tujuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tujuMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tujuMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int total = 50000;
        if(jumlah.getText().trim().isEmpty() || tuju.getText().trim().isEmpty()){
            salah.setText("Mohon Masukkan Jumlah Pengiriman yang Benar");
            
        }else if(Integer.parseInt(jumlah.getText()) < total){
                salah.setText("Minimum Transfer adalah 50000 Beserta Kelipatannya");
            
         }else{
            int trans = Integer.parseInt(jumlah.getText());
            tabu -= trans;
            String tujuan = tuju.getText().toString();
            String jumlahan = jumlah.getText().toString();
            
            salah.setText("");
            salah.setText("TRANSAKSI BERHASIL"
                    + "\nDENGAN NOMOR TUJUAN "+tujuan+" SEJUMLAH "+jumlahan
                    + " \n\nMAKA SISA TABUNGAN ANDA "+tabu);
            
            lagi.setVisible(true);
            hilang.setVisible(true);
            tidak.setVisible(true);
           
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lagiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lagiActionPerformed

    private void tidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakActionPerformed

    private void tidakMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tidakMouseReleased
       System.exit(0);
    }//GEN-LAST:event_tidakMouseReleased

    private void lagiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lagiMouseReleased
        new Password().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lagiMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hilang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JButton lagi;
    private javax.swing.JTextArea salah;
    private javax.swing.JButton tidak;
    private javax.swing.JTextField tuju;
    // End of variables declaration//GEN-END:variables
}
